### ISSUE TITLE
weird item rendering & deposing

### ISSUE THREAD

**Issue by N1cohd1** [MuffinGroup/yet-to-be-named-game#48]
If tha player is behind a cloud, the item is in front of the cloud (the same with speech bubbles). If he goes through a door and he's going invisible, the item isn't. The player isn't able to pick up items from pedestals. The item doesn't follow the hand while running.

**Comment by N1cohd1** [comment]
Also, the item is flying upon the pedestal

**Comment by Thepigcat76** [comment]
fixed (mostly)
