### ISSUE TITLE
FLYING

### ISSUE THREAD

**Issue by N1cohd1** [MuffinGroup/yet-to-be-named-game#65]
Huge problems with flying are:
-If you jump to the ceiling, press "u" and let go of the jump key, you copletely glitch through the ceiling
-If you press "LEFT" while glitched into the blocks, you teleport to the right really fast
-If you press "UP" while glitched into the blocks, you teleport to the down really fast
-Flying is technically just a high jump

**Comment by Thepigcat76** [comment]
flying only exists for debugging so I wont fix any issues regarding that
