### ISSUE TITLE
One long Issue thing

### ISSUE THREAD

**Issue by N1cohd1** [MuffinGroup/yet-to-be-named-game#76]
-Walking in tut2 is too fast
-The Pillar in tut2 after the explosion isn't broken or anything
Screenshot:
![image](https://github.com/MuffinGroup/yet-to-be-named-game/assets/125882726/5c4e5354-e7ff-4cc6-9b97-6396a6440980)
- Item still flies upon pedestal
- Hitbox of pedestal isn't right (to high)
- Debug Mode settings don't transfer across worlds (not that important, but QOL bad)
- Yellow Banner is cut off at the bottom
Screenshot:
![image](https://github.com/MuffinGroup/yet-to-be-named-game/assets/125882726/97166974-4700-415b-9d31-64aed574bee2)
-Tictactoe Icons are (sorry) so bad
-Hot Air:
       -Tictactoe gets replaced by Hot Air
       -Hot Air animation too fast
       -Player flies up too fast
       -no building animation of the hot air from bottom to top
       -if player falls down from the air, he can't get back up
-Door in world 3 isn't half in the wall like it should be
-You can see the end of the world in world 3 (bottom and right of the world

**Comment by Thepigcat76** [comment]
Most of this has been fixed :D
